default_connection_name = "SF_Dinesh2012"

[SF_Dinesh2012]
account = "ELB35621"
user = "DKUMARJAYAKUMAR"
password = "Vivega@11223344"
database = "DOC_CHATBOT_DB"
schema = "PUBLIC"
warehouse = "DOC_CHATBOT_WH"
role = "ACCOUNTADMIN"



