default_connection_name = "SF_Dinesh2012"

[SF_Dinesh2012]
account = "JFB66155"
user = "ADMIN"
password = "Admin@11223344"
database = "DOC_CHATBOT_DB"
schema = "PUBLIC"
warehouse = "DOC_CHATBOT_WH"
role = "ACCOUNTADMIN"



